# Generated by Django 4.2.3 on 2023-11-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Username',
        ),
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(max_length=122),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
