# Generated by Django 4.2.7 on 2023-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_remove_login_username_alter_login_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=122, null=True)),
                ('email1', models.CharField(max_length=122, null=True)),
                ('password', models.CharField(max_length=122, null=True)),
                ('conform', models.CharField(max_length=122, null=True)),
            ],
        ),
    ]
