# Generated by Django 4.2.7 on 2023-11-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0003_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='conform',
            new_name='comform',
        ),
    ]
